import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx-js-style';
import { getCrednivoLogoDataUrl } from './reportBrand';

const INR = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });

function safeText(value, fallback = '—') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

function fileBase(cycle) {
  const slug = String(cycle || 'all').trim().toLowerCase().replace(/\s+/g, '-');
  return `crednivo-customers-${slug}`;
}

function downloadBlob(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1200);
}

async function urlToPngDataUrl(url) {
  if (!url) return '';
  try {
    const image = new Image();
    image.crossOrigin = 'anonymous';
    const loaded = new Promise((resolve, reject) => {
      image.onload = resolve;
      image.onerror = reject;
    });
    image.src = url;
    await loaded;
    const canvas = document.createElement('canvas');
    canvas.width = Math.max(1, image.naturalWidth || 1);
    canvas.height = Math.max(1, image.naturalHeight || 1);
    const ctx = canvas.getContext('2d');
    ctx.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL('image/png');
  } catch {
    return '';
  }
}

function drawHeader(doc, pageWidth, margin, companyLogo, company) {
  let textX = margin;
  if (companyLogo) {
    try {
      doc.addImage(companyLogo, 'PNG', margin, 10, 17, 17, undefined, 'FAST');
      textX = margin + 21;
    } catch {
      textX = margin;
    }
  }

  doc.setTextColor(15, 32, 58);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(safeText(company?.name, 'Company'), textX, 16);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(94, 111, 135);
  doc.text(safeText(company?.branch, 'Main Branch'), textX, 22);

  doc.setDrawColor(221, 229, 239);
  doc.line(margin, 31, pageWidth - margin, 31);
}

function drawFooter(doc, pageWidth, pageHeight, margin, pageNo, totalPages, crednivoLogo) {
  const y = pageHeight - 14;
  doc.setDrawColor(231, 236, 243);
  doc.line(margin, y - 7, pageWidth - margin, y - 7);

  const logoX = pageWidth - margin - 48;
  if (crednivoLogo) {
    try { doc.addImage(crednivoLogo, 'PNG', logoX, y - 4.5, 8, 7.5, undefined, 'FAST'); } catch { /* optional */ }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.2);
  doc.setTextColor(12, 48, 86);
  doc.text('CREDNIVO', logoX + 10, y - 1);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(105, 120, 141);
  doc.text('Finance Management Platform', logoX + 10, y + 3);
  doc.text(`Page ${pageNo} of ${totalPages}`, margin, y + 2);
}

export async function exportCustomersListPdf({ cycle, generatedBy, company, rows }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape', compress: true });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;

  const [companyLogo, crednivoLogo] = await Promise.all([
    urlToPngDataUrl(company?.logo),
    getCrednivoLogoDataUrl().catch(() => ''),
  ]);

  drawHeader(doc, pageWidth, margin, companyLogo, company);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(10, 27, 48);
  doc.text(`${safeText(cycle, 'All')} Customers List`, margin, 41);

  autoTable(doc, {
    startY: 46,
    body: [
      ['Generated by', safeText(generatedBy, 'Admin')],
      ['Total Customers', String(Array.isArray(rows) ? rows.length : 0)],
    ],
    theme: 'plain',
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.3, cellPadding: 1.3, textColor: [48, 65, 88] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 28, textColor: [65, 82, 105] },
      1: { textColor: [15, 31, 52] },
    },
  });

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 5,
    head: [['Customer', 'Phone', 'Witness', 'Witness Phone', 'Cycle', 'Active Loan', 'Closed Loan', 'Outstanding']],
    body: (Array.isArray(rows) ? rows : []).map((row) => ([
      `${safeText(row.name)}\n${safeText(row.id)}`,
      safeText(row.phone),
      safeText(row.witnessName),
      safeText(row.witnessPhone),
      safeText(row.cycle),
      String(row.activeLoans ?? 0),
      String(row.closedLoans ?? 0),
      Number(row.outstanding || 0),
    ])),
    margin: { top: 36, bottom: 27, left: margin, right: margin },
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 7.4,
      cellPadding: 2.1,
      lineColor: [224, 231, 240],
      lineWidth: 0.18,
      textColor: [22, 37, 58],
      valign: 'middle',
    },
    headStyles: {
      fillColor: [15, 84, 148],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.3,
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 28 },
      2: { cellWidth: 34 },
      3: { cellWidth: 30 },
      4: { cellWidth: 22 },
      5: { cellWidth: 21, halign: 'center' },
      6: { cellWidth: 21, halign: 'center' },
      7: { cellWidth: 26, halign: 'right' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 7 && typeof data.cell.raw === 'number') {
        data.cell.text = [INR.format(data.cell.raw)];
      }
    },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) drawHeader(doc, pageWidth, margin, companyLogo, company);
    },
  });

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    drawFooter(doc, pageWidth, pageHeight, margin, page, pages, crednivoLogo);
  }

  doc.save(`${fileBase(cycle)}.pdf`);
}

export async function exportCustomersListXlsx({ cycle, generatedBy, company, rows }) {
  const headerStyle = {
    font: { bold: true, color: { rgb: 'FFFFFF' } },
    fill: { fgColor: { rgb: '0F5494' } },
    alignment: { vertical: 'center', horizontal: 'center' },
    border: {
      top: { style: 'thin', color: { rgb: 'D9E2EF' } },
      bottom: { style: 'thin', color: { rgb: 'D9E2EF' } },
      left: { style: 'thin', color: { rgb: 'D9E2EF' } },
      right: { style: 'thin', color: { rgb: 'D9E2EF' } },
    },
  };

  const bodyStyle = {
    alignment: { vertical: 'top', wrapText: true },
    border: {
      top: { style: 'thin', color: { rgb: 'E6ECF4' } },
      bottom: { style: 'thin', color: { rgb: 'E6ECF4' } },
      left: { style: 'thin', color: { rgb: 'E6ECF4' } },
      right: { style: 'thin', color: { rgb: 'E6ECF4' } },
    },
  };

  const rowsAoa = [
    [safeText(company?.name, 'Company')],
    [safeText(company?.branch, 'Main Branch')],
    [`${safeText(cycle, 'All')} Customers List`],
    [`Generated by: ${safeText(generatedBy, 'Admin')}`],
    [],
    ['Customer', 'Phone', 'Witness', 'Witness Phone', 'Cycle', 'Active Loan', 'Closed Loan', 'Outstanding'],
    ...(Array.isArray(rows) ? rows : []).map((row) => ([
      `${safeText(row.name)}\n${safeText(row.id)}`,
      safeText(row.phone),
      safeText(row.witnessName),
      safeText(row.witnessPhone),
      safeText(row.cycle),
      Number(row.activeLoans || 0),
      Number(row.closedLoans || 0),
      Number(row.outstanding || 0),
    ])),
  ];

  const ws = XLSX.utils.aoa_to_sheet(rowsAoa);
  ws['!cols'] = [
    { wch: 28 },
    { wch: 18 },
    { wch: 20 },
    { wch: 18 },
    { wch: 14 },
    { wch: 12 },
    { wch: 12 },
    { wch: 16 },
  ];
  ws['!merges'] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 7 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: 7 } },
    { s: { r: 2, c: 0 }, e: { r: 2, c: 7 } },
    { s: { r: 3, c: 0 }, e: { r: 3, c: 7 } },
  ];

  const range = XLSX.utils.decode_range(ws['!ref']);
  for (let c = 0; c <= 7; c += 1) {
    const headerCellRef = XLSX.utils.encode_cell({ r: 5, c });
    if (ws[headerCellRef]) ws[headerCellRef].s = headerStyle;
  }

  for (let r = 6; r <= range.e.r; r += 1) {
    for (let c = 0; c <= 7; c += 1) {
      const ref = XLSX.utils.encode_cell({ r, c });
      if (!ws[ref]) continue;
      ws[ref].s = bodyStyle;
      if (c === 7) {
        ws[ref].t = 'n';
        ws[ref].z = '₹#,##0';
      }
    }
  }

  ['A1', 'A2', 'A3', 'A4'].forEach((ref, index) => {
    if (!ws[ref]) return;
    ws[ref].s = {
      font: { bold: index < 3, sz: index === 0 ? 15 : index === 2 ? 12 : 10, color: { rgb: index < 3 ? '0F203A' : '5E6F87' } },
      alignment: { horizontal: 'left', vertical: 'center' },
    };
  });

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Customers');
  const array = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
  downloadBlob(new Blob([array], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${fileBase(cycle)}.xlsx`);
}
