import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx-js-style';
import { getCrednivoLogoDataUrl } from './reportBrand';

// History (payments ledger) export — same PDF / XLSX format family as the
// Today's Collection and Customers exports.

const INR = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const HEAD = ['Date', 'Transaction', 'Customer / Purpose', 'Reference', 'Mode', 'Details', 'Direction', 'Amount'];

function safeText(value, fallback = '—') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

function rangeLabel(fromDate, toDate) {
  if (!fromDate && !toDate) return 'All dates';
  if (fromDate && fromDate === toDate) return fromDate;
  return `${fromDate || 'Start'} to ${toDate || 'Latest'}`;
}

function fileBase(fromDate, toDate) {
  return `crednivo-history-${fromDate || 'start'}-to-${toDate || 'latest'}`;
}

function rowValues(item, details) {
  return [
    safeText(item.date),
    safeText(item.type),
    safeText(item.customerName),
    safeText(item.loanId || item.customerId),
    safeText(item.paymentMode),
    safeText(details(item)),
    item.direction === 'in' ? 'Incoming' : 'Outgoing',
    Number(item.amount) || 0,
  ];
}

function downloadBlob(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1200);
}

async function urlToPngDataUrl(url) {
  if (!url) return '';
  try {
    const image = new Image();
    image.crossOrigin = 'anonymous';
    const loaded = new Promise((resolve, reject) => { image.onload = resolve; image.onerror = reject; });
    image.src = url;
    await loaded;
    const canvas = document.createElement('canvas');
    canvas.width = Math.max(1, image.naturalWidth || 1);
    canvas.height = Math.max(1, image.naturalHeight || 1);
    canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL('image/png');
  } catch {
    return '';
  }
}

function drawHeader(doc, pageWidth, margin, companyLogo, company) {
  let textX = margin;
  if (companyLogo) {
    try { doc.addImage(companyLogo, 'PNG', margin, 10, 17, 17, undefined, 'FAST'); textX = margin + 21; } catch { textX = margin; }
  }
  doc.setTextColor(15, 32, 58);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(safeText(company?.name, 'Company'), textX, 16);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(94, 111, 135);
  doc.text(safeText(company?.branch, 'Main Branch'), textX, 22);
  doc.setDrawColor(221, 229, 239);
  doc.line(margin, 31, pageWidth - margin, 31);
}

function drawFooter(doc, pageWidth, pageHeight, margin, pageNo, totalPages, crednivoLogo) {
  const y = pageHeight - 14;
  doc.setDrawColor(231, 236, 243);
  doc.line(margin, y - 7, pageWidth - margin, y - 7);
  const logoX = pageWidth - margin - 48;
  if (crednivoLogo) {
    try { doc.addImage(crednivoLogo, 'PNG', logoX, y - 4.5, 8, 7.5, undefined, 'FAST'); } catch { /* optional */ }
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.2);
  doc.setTextColor(12, 48, 86);
  doc.text('CREDNIVO', logoX + 10, y - 1);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(105, 120, 141);
  doc.text('Finance Management Platform', logoX + 10, y + 3);
  doc.text(`Page ${pageNo} of ${totalPages}`, margin, y + 2);
}

export async function exportHistoryPdf({ company, generatedBy, fromDate, toDate, filter, rows, totals, details }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape', compress: true });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;
  const [companyLogo, crednivoLogo] = await Promise.all([
    urlToPngDataUrl(company?.logo),
    getCrednivoLogoDataUrl().catch(() => ''),
  ]);

  drawHeader(doc, pageWidth, margin, companyLogo, company);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(10, 27, 48);
  doc.text('Transaction History', margin, 41);

  autoTable(doc, {
    startY: 46,
    body: [
      ['Date range', rangeLabel(fromDate, toDate)],
      ['Transaction type', safeText(filter, 'All')],
      ['Generated by', safeText(generatedBy, 'Admin')],
      ['Total incoming', INR.format(totals.incoming || 0)],
      ['Total outgoing', INR.format(totals.outgoing || 0)],
      ['Net cash flow', INR.format((totals.incoming || 0) - (totals.outgoing || 0))],
    ],
    theme: 'plain',
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.3, cellPadding: 1.3, textColor: [48, 65, 88] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 32, textColor: [65, 82, 105] }, 1: { textColor: [15, 31, 52] } },
  });

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 5,
    head: [HEAD],
    body: rows.map((item) => rowValues(item, details)),
    margin: { top: 36, bottom: 27, left: margin, right: margin },
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 7.4, cellPadding: 2.1, lineColor: [224, 231, 240], lineWidth: 0.18, textColor: [22, 37, 58], valign: 'middle' },
    headStyles: { fillColor: [15, 84, 148], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.3 },
    columnStyles: {
      0: { cellWidth: 22 }, 1: { cellWidth: 26 }, 2: { cellWidth: 40 }, 3: { cellWidth: 30 },
      4: { cellWidth: 18 }, 5: { cellWidth: 'auto' }, 6: { cellWidth: 20 }, 7: { cellWidth: 26, halign: 'right' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 7 && typeof data.cell.raw === 'number') {
        const incoming = data.row.raw[6] === 'Incoming';
        data.cell.text = [`${incoming ? '+' : '−'} ${INR.format(data.cell.raw)}`];
        data.cell.styles.textColor = incoming ? [22, 139, 64] : [214, 69, 69];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    didDrawPage: (data) => { if (data.pageNumber > 1) drawHeader(doc, pageWidth, margin, companyLogo, company); },
  });

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    drawFooter(doc, pageWidth, pageHeight, margin, page, pages, crednivoLogo);
  }
  doc.save(`${fileBase(fromDate, toDate)}.pdf`);
}

export async function exportHistoryXlsx({ company, generatedBy, fromDate, toDate, filter, rows, totals, details }) {
  const border = (rgb) => ({ top: { style: 'thin', color: { rgb } }, bottom: { style: 'thin', color: { rgb } }, left: { style: 'thin', color: { rgb } }, right: { style: 'thin', color: { rgb } } });
  const headerStyle = { font: { bold: true, color: { rgb: 'FFFFFF' } }, fill: { fgColor: { rgb: '0F5494' } }, alignment: { vertical: 'center', horizontal: 'center' }, border: border('D9E2EF') };
  const bodyStyle = { alignment: { vertical: 'top', wrapText: true }, border: border('E6ECF4') };
  const titleStyle = { font: { bold: true, sz: 14, color: { rgb: '0A1B30' } } };

  const aoa = [
    [safeText(company?.name, 'Company')],
    [safeText(company?.branch, 'Main Branch')],
    ['Transaction History'],
    [`Date range: ${rangeLabel(fromDate, toDate)}   |   Type: ${safeText(filter, 'All')}   |   Generated by: ${safeText(generatedBy, 'Admin')}`],
    [`Incoming: ${INR.format(totals.incoming || 0)}   |   Outgoing: ${INR.format(totals.outgoing || 0)}   |   Net: ${INR.format((totals.incoming || 0) - (totals.outgoing || 0))}`],
    [],
    HEAD,
    ...rows.map((item) => rowValues(item, details)),
  ];
  const headerRow = 6;
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws['!cols'] = [{ wch: 12 }, { wch: 16 }, { wch: 26 }, { wch: 18 }, { wch: 10 }, { wch: 40 }, { wch: 11 }, { wch: 14 }];
  ws['!merges'] = [0, 1, 2, 3, 4].map((r) => ({ s: { r, c: 0 }, e: { r, c: 7 } }));
  if (ws.A1) ws.A1.s = titleStyle;
  if (ws.A3) ws.A3.s = titleStyle;

  const range = XLSX.utils.decode_range(ws['!ref']);
  for (let c = 0; c <= 7; c += 1) {
    const ref = XLSX.utils.encode_cell({ r: headerRow, c });
    if (ws[ref]) ws[ref].s = headerStyle;
  }
  for (let r = headerRow + 1; r <= range.e.r; r += 1) {
    for (let c = 0; c <= 7; c += 1) {
      const ref = XLSX.utils.encode_cell({ r, c });
      if (!ws[ref]) continue;
      ws[ref].s = bodyStyle;
      if (c === 7) { ws[ref].z = '"₹"#,##0'; ws[ref].s = { ...bodyStyle, alignment: { horizontal: 'right' } }; }
    }
  }

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'History');
  const array = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
  downloadBlob(new Blob([array], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${fileBase(fromDate, toDate)}.xlsx`);
}
