import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';

function number(value) {
  return Number(value) || 0;
}

function inr(value) {
  return `INR ${Math.round(number(value)).toLocaleString('en-IN')}`;
}

function safe(value, fallback = '-') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

function titleCase(value) {
  const text = safe(value, '');
  return text ? text[0].toUpperCase() + text.slice(1) : text;
}

function reportId(monthKey) {
  return `CREDNIVO-MR-${String(monthKey || '').replace('-', '')}`;
}

function addPageFooter(doc, companyName) {
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    const width = doc.internal.pageSize.getWidth();
    const height = doc.internal.pageSize.getHeight();

    doc.setDrawColor(225, 231, 239);
    doc.line(14, height - 13, width - 14, height - 13);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by CREDNIVO for ${safe(companyName, 'Company')}`, 14, height - 7.5);
    doc.text(`Page ${page} of ${pages}`, width - 14, height - 7.5, { align: 'right' });
  }
}

function sectionHeading(doc, text, y) {
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(14, y, 182, 8.5, 2, 2, 'F');
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.text(text, 18, y + 5.8);
  return y + 11;
}

function ensureSpace(doc, y, needed = 35) {
  const height = doc.internal.pageSize.getHeight();
  if (y + needed < height - 18) return y;
  doc.addPage();
  return 18;
}

export function downloadMonthlyReportPdf({ report, selectedMonth, company }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const generatedAt = new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date());

  // Header band
  doc.setFillColor(7, 49, 89);
  doc.rect(0, 0, pageWidth, 36, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('CREDNIVO', 14, 15);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text('Finance Management Platform', 14, 21);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('MONTHLY BUSINESS REPORT', pageWidth - 14, 13, { align: 'right' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(report.month.label, pageWidth - 14, 20, { align: 'right' });
  doc.setFontSize(7.5);
  doc.text(reportId(selectedMonth), pageWidth - 14, 26, { align: 'right' });

  let y = 44;
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(safe(company?.name, 'Company'), 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`${safe(company?.branch, 'Main Branch')}  |  ${safe(company?.mobile, 'No mobile')}`, 14, y + 5);
  if (company?.address) doc.text(safe(company.address), 14, y + 10);

  doc.setFontSize(7.5);
  doc.text(`Generated: ${generatedAt}`, pageWidth - 14, y, { align: 'right' });
  doc.text(`Report Period: ${report.month.start} to ${report.month.end}`, pageWidth - 14, y + 5, { align: 'right' });
  y += 18;

  y = sectionHeading(doc, '1. Collection Summary', y);
  autoTable(doc, {
    startY: y,
    head: [['Collection Cycle', 'Collected Amount']],
    body: [
      ...report.cycles.map((item) => [item.cycle, inr(item.collected)]),
      ['Overall Collection', inr(report.overallCollected)],
    ],
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 3, textColor: [30, 41, 59], lineColor: [226, 232, 240], lineWidth: 0.15 },
    headStyles: { fillColor: [30, 111, 232], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === report.cycles.length) {
        data.cell.styles.fillColor = [239, 246, 255];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });
  y = doc.lastAutoTable.finalY + 7;

  y = ensureSpace(doc, y, 45);
  y = sectionHeading(doc, '2. Customer / Loan Portfolio', y);
  autoTable(doc, {
    startY: y,
    head: [['Cycle', 'Customers', 'Loans', 'Customers / Loans']],
    body: [
      ...report.cycles.map((item) => [item.cycle, item.customers, item.loans, `${item.customers} / ${item.loans}`]),
      ['Total', report.totalCustomers, report.totalLoans, `${report.totalCustomers} / ${report.totalLoans}`],
    ],
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 8.7, cellPadding: 2.8, lineColor: [226, 232, 240], lineWidth: 0.15 },
    headStyles: { fillColor: [15, 64, 110], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center', fontStyle: 'bold' } },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === report.cycles.length) {
        data.cell.styles.fillColor = [248, 250, 252];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });
  y = doc.lastAutoTable.finalY + 7;

  y = ensureSpace(doc, y, 63);
  y = sectionHeading(doc, '3. Monthly Finance Summary', y);
  autoTable(doc, {
    startY: y,
    head: [['Particulars', 'Amount']],
    body: [
      ['Expected Collection', inr(report.overallExpected)],
      ['Actual Collection', inr(report.overallCollected)],
      ['Pending', inr(report.overallPending)],
      ['Overdue', inr(report.overdueAmount)],
      ['New Loans Given', inr(report.newLoansGiven)],
      ['Expenses', inr(report.expenseTotal)],
      ['Net Cash Flow', inr(report.netCash)],
    ],
    theme: 'striped',
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 3, lineColor: [226, 232, 240], lineWidth: 0.1 },
    headStyles: { fillColor: [30, 111, 232], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === 6) {
        data.cell.styles.fillColor = report.netCash >= 0 ? [232, 248, 238] : [255, 238, 240];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = report.netCash >= 0 ? [18, 132, 60] : [209, 55, 72];
      }
    },
  });
  y = doc.lastAutoTable.finalY + 7;

  y = ensureSpace(doc, y, 58);
  y = sectionHeading(doc, '4. Cycle Performance', y);
  autoTable(doc, {
    startY: y,
    head: [['Cycle', 'Expected', 'Collected', 'Pending', 'Paid / Unpaid', 'Rate']],
    body: report.cycles.map((item) => [
      item.cycle,
      inr(item.expected),
      inr(item.collected),
      inr(item.pending),
      `${item.paidEntries} / ${item.unpaidEntries}`,
      `${item.rate.toFixed(1)}%`,
    ]),
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 7.7, cellPadding: 2.5, lineColor: [226, 232, 240], lineWidth: 0.15 },
    headStyles: { fillColor: [15, 64, 110], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'center' }, 5: { halign: 'center', fontStyle: 'bold' } },
  });
  y = doc.lastAutoTable.finalY + 7;

  y = ensureSpace(doc, y, 55);
  y = sectionHeading(doc, '5. Monthly Activity and Recovery', y);
  autoTable(doc, {
    startY: y,
    head: [['Monthly Activity', 'Count', 'Recovery Summary', 'Value']],
    body: [
      ['New Customers', report.newCustomers, 'Pending Amount', inr(report.overallPending)],
      ['New Loans', report.newLoans, 'Overdue Amount', inr(report.overdueAmount)],
      ['Closed Loans', report.closedLoans, 'Pending Customers', report.pendingCustomers],
      ['Transactions', report.transactions, 'Overdue Customers', report.overdueCustomers],
    ],
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 3, lineColor: [226, 232, 240], lineWidth: 0.15 },
    headStyles: { fillColor: [30, 111, 232], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'center', fontStyle: 'bold' }, 3: { halign: 'right', fontStyle: 'bold' } },
  });
  y = doc.lastAutoTable.finalY + 7;

  y = ensureSpace(doc, y, 80);
  y = sectionHeading(doc, '6. Daily Collection Breakdown', y);
  const trendRows = report.trend
    .filter((item) => item.amount > 0)
    .map((item) => [
      `${String(item.day).padStart(2, '0')} ${report.month.label}`,
      inr(item.amount),
    ]);

  autoTable(doc, {
    startY: y,
    head: [['Collection Date', 'Amount Collected']],
    body: trendRows.length ? trendRows : [['No collection recorded for this month', '-']],
    foot: trendRows.length ? [['Total', inr(report.overallCollected)]] : undefined,
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 2.7, lineColor: [226, 232, 240], lineWidth: 0.15 },
    headStyles: { fillColor: [15, 64, 110], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [239, 246, 255], textColor: [15, 23, 42], fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  if (finalY < doc.internal.pageSize.getHeight() - 30) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text('Note: This report is generated from the records currently available in CREDNIVO for the selected month.', 14, finalY);
  }

  addPageFooter(doc, company?.name);
  doc.save(`CREDNIVO_Monthly_Report_${String(report.month.label).replace(/\s+/g, '_')}.pdf`);
}
